### ISSUE TITLE
Automatic creation

### ISSUE THREAD

**Issue by Ortuna** [wikimatze/padrino-zsh-completion#1]
I was thinking about this the other day!  But I wonder if there is a way to automatically create these?

**Comment by wikimatze** [comment]
What do you exactly mean? The commands with the text?

**Comment by Ortuna** [comment]
Woops, meaning that when ever padrino updates => the completions update.  Should be possible since Padrino uses Thor?

But I don't know if that goes along with your initial intent.

**Comment by wikimatze** [comment]
Interesting idea ... nope, this wasn't on my agenda when I wrote this plugin. Not used to Thor, first I have to learn it.
