### ISSUE TITLE
Credit MIT license

### ISSUE THREAD

**Issue by hiepph** [wikimatze/padrino-zsh-completion#9]
Hello, i want to use your `padrino-zsh-completion` script to contribute to `zsh plugins`. And credit in my `_padrino` like this:

```
#
#  CREDIT:
#   This padrino completion script is referenced from project below
#
#   * Origin      : padrino-zsh-completion
#   * Author      : Matthias Günther <matthias.guenther@wikimatze.de>
#   * Github      : @wikimatze
#   * License     : MIT License
#   * Repository  : https://github.com/wikimatze/padrino-zsh-completion
#
#   Best regard for hardwork
#
```

And future i may have some changes which means edit your code, is this OK for me to do these things ? Thanks in advance.

**Comment by wikimatze** [comment]
That's fine. Do you want to include it to oh-my-zsh shell? I have think of that but found it more easier to have this code on my own => not so many people are using Padrino and not all want to have this which may have a little performance impact for the other completion tools.

**Comment by hiepph** [comment]
Ah, exactly i want to contribute `oh-my-zsh` shell. My team is using Padrino and i think this contribute may increase some performances :)

**Comment by wikimatze** [comment]
Hi @hiepph can you post me the project/repo where you have used it?

**Comment by hiepph** [comment]
Oops, sorry, I ended up using personally only :( And it's been a long time since I touched Padrino.

**Comment by wikimatze** [comment]
No problem, if you find yourself sometime in the future in the need to use Padrino and my completion tool, then just let me know. I'll close this issue then.
